[forest]
host = "trebor"
trees = ["trees/"]
assets = ["assets"]
theme = "theme"
home = "trebor-0001"
base_url = "https://trebor-huang.github.io/forest/"
prefixes = ["trebor", "tile", "ualg", "hmlg", "algm", "misc", "cplx"]
